image: docker:latest
stages:
  - build

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

before_script:
    - if [ "$CI_COMMIT_REF_NAME" != "master" ]; then BRANCH="/$CI_COMMIT_REF_NAME"; fi
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t "$CI_REGISTRY_IMAGE$BRANCH:latest" .
    - docker push "$CI_REGISTRY_IMAGE$BRANCH:latest"
    # Publish to dockerhub
    - >
      if [ -z "$BRANCH" ] && [ ! -z "$DOCKERHUB_PASSWORD" ]; then
        docker login -u "$DOCKERHUB_LOGIN" -p "$DOCKERHUB_PASSWORD";
        docker tag "$CI_REGISTRY_IMAGE$BRANCH:latest" thann/rabbit-cron;
        docker push thann/rabbit-cron; fi

